name: MAMEUI Builds

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          msystem: MINGW32
          location: D:\
          install: >-
            zip
            unzip
            p7zip
            git
            make
            mingw-w64-i686-toolchain
            mingw-w64-i686-SDL2 
            mingw-w64-i686-SDL2_ttf
            mingw-w64-i686-python

      # Runs a set of commands using the runners shell
      - name: build32
        shell: msys2 {0}
        run: |
          wget -q https://repo.mamedev.org/i686/mame-essentials-1.0.0-1-i686.pkg.tar.xz
          pacman -U *.pkg.tar.xz
          git clone https://github.com/Robbbert/mameui.git
          cd mameui/
          make OSD=messui PTR64=0 SYMBOLS=0 NO_SYMBOLS=1 DEPRECATED=0

      - uses: actions/upload-artifact@v4
        with:
          name: mameui
          path: ${{ github.workspace }}\codeblocks_sfmirror\src\devel32
      
